// Code generated by protoc-gen-go.
// source: account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	Account
	CreateAcctRequest
	CreateAcctResponse
	ListAcctRequest
	ListAcctResponse
	ShowAcctRequest
	ShowAcctResponse
	DeleteAcctRequest
	DeleteAcctResponse
	UpdateAcctRequest
	UpdateAcctResponse
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

// Account Profile
type Account struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Apikey     string `protobuf:"bytes,3,opt,name=apikey" json:"apikey,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	CreateDate int64  `protobuf:"varint,5,opt,name=createDate" json:"createDate,omitempty"`
	DeleteDate int64  `protobuf:"varint,6,opt,name=deleteDate" json:"deleteDate,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Request to Create an account
type CreateAcctRequest struct {
	Acct     string `protobuf:"bytes,1,opt,name=acct" json:"acct,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *CreateAcctRequest) Reset()                    { *m = CreateAcctRequest{} }
func (m *CreateAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAcctRequest) ProtoMessage()               {}
func (*CreateAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Response for account Create results
type CreateAcctResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *CreateAcctResponse) Reset()                    { *m = CreateAcctResponse{} }
func (m *CreateAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAcctResponse) ProtoMessage()               {}
func (*CreateAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Request to show an account
type ListAcctRequest struct {
	Superkey string `protobuf:"bytes,1,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *ListAcctRequest) Reset()                    { *m = ListAcctRequest{} }
func (m *ListAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*ListAcctRequest) ProtoMessage()               {}
func (*ListAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Response for account Show results
type ListAcctResponse struct {
	Account []*Account `protobuf:"bytes,1,rep,name=account" json:"account,omitempty"`
	Status  string     `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ListAcctResponse) Reset()                    { *m = ListAcctResponse{} }
func (m *ListAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAcctResponse) ProtoMessage()               {}
func (*ListAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListAcctResponse) GetAccount() []*Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// Request to show an account
type ShowAcctRequest struct {
	Acct     string `protobuf:"bytes,1,opt,name=acct" json:"acct,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *ShowAcctRequest) Reset()                    { *m = ShowAcctRequest{} }
func (m *ShowAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*ShowAcctRequest) ProtoMessage()               {}
func (*ShowAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// Response for account Show results
type ShowAcctResponse struct {
	Account *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Status  string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ShowAcctResponse) Reset()                    { *m = ShowAcctResponse{} }
func (m *ShowAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*ShowAcctResponse) ProtoMessage()               {}
func (*ShowAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ShowAcctResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// Request to Delete account
type DeleteAcctRequest struct {
	Acct     string `protobuf:"bytes,1,opt,name=acct" json:"acct,omitempty"`
	Superkey string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
}

func (m *DeleteAcctRequest) Reset()                    { *m = DeleteAcctRequest{} }
func (m *DeleteAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAcctRequest) ProtoMessage()               {}
func (*DeleteAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Response for account Delete results
type DeleteAcctResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *DeleteAcctResponse) Reset()                    { *m = DeleteAcctResponse{} }
func (m *DeleteAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAcctResponse) ProtoMessage()               {}
func (*DeleteAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// Request to Update account's api key
type UpdateAcctRequest struct {
	Acct      string `protobuf:"bytes,1,opt,name=acct" json:"acct,omitempty"`
	Superkey  string `protobuf:"bytes,2,opt,name=superkey" json:"superkey,omitempty"`
	Newapikey string `protobuf:"bytes,3,opt,name=newapikey" json:"newapikey,omitempty"`
}

func (m *UpdateAcctRequest) Reset()                    { *m = UpdateAcctRequest{} }
func (m *UpdateAcctRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateAcctRequest) ProtoMessage()               {}
func (*UpdateAcctRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// Response for account Update results
type UpdateAcctResponse struct {
	Account *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Status  string   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateAcctResponse) Reset()                    { *m = UpdateAcctResponse{} }
func (m *UpdateAcctResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateAcctResponse) ProtoMessage()               {}
func (*UpdateAcctResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateAcctResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterType((*CreateAcctRequest)(nil), "account.CreateAcctRequest")
	proto.RegisterType((*CreateAcctResponse)(nil), "account.CreateAcctResponse")
	proto.RegisterType((*ListAcctRequest)(nil), "account.ListAcctRequest")
	proto.RegisterType((*ListAcctResponse)(nil), "account.ListAcctResponse")
	proto.RegisterType((*ShowAcctRequest)(nil), "account.ShowAcctRequest")
	proto.RegisterType((*ShowAcctResponse)(nil), "account.ShowAcctResponse")
	proto.RegisterType((*DeleteAcctRequest)(nil), "account.DeleteAcctRequest")
	proto.RegisterType((*DeleteAcctResponse)(nil), "account.DeleteAcctResponse")
	proto.RegisterType((*UpdateAcctRequest)(nil), "account.UpdateAcctRequest")
	proto.RegisterType((*UpdateAcctResponse)(nil), "account.UpdateAcctResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for AccountApi service

type AccountApiClient interface {
	CreateAcct(ctx context.Context, in *CreateAcctRequest, opts ...grpc.CallOption) (*CreateAcctResponse, error)
	ListAcct(ctx context.Context, in *ListAcctRequest, opts ...grpc.CallOption) (*ListAcctResponse, error)
	ShowAcct(ctx context.Context, in *ShowAcctRequest, opts ...grpc.CallOption) (*ShowAcctResponse, error)
	DeleteAcct(ctx context.Context, in *DeleteAcctRequest, opts ...grpc.CallOption) (*DeleteAcctResponse, error)
	UpdateAcct(ctx context.Context, in *UpdateAcctRequest, opts ...grpc.CallOption) (*UpdateAcctResponse, error)
}

type accountApiClient struct {
	cc *grpc.ClientConn
}

func NewAccountApiClient(cc *grpc.ClientConn) AccountApiClient {
	return &accountApiClient{cc}
}

func (c *accountApiClient) CreateAcct(ctx context.Context, in *CreateAcctRequest, opts ...grpc.CallOption) (*CreateAcctResponse, error) {
	out := new(CreateAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/CreateAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) ListAcct(ctx context.Context, in *ListAcctRequest, opts ...grpc.CallOption) (*ListAcctResponse, error) {
	out := new(ListAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/ListAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) ShowAcct(ctx context.Context, in *ShowAcctRequest, opts ...grpc.CallOption) (*ShowAcctResponse, error) {
	out := new(ShowAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/ShowAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) DeleteAcct(ctx context.Context, in *DeleteAcctRequest, opts ...grpc.CallOption) (*DeleteAcctResponse, error) {
	out := new(DeleteAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/DeleteAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountApiClient) UpdateAcct(ctx context.Context, in *UpdateAcctRequest, opts ...grpc.CallOption) (*UpdateAcctResponse, error) {
	out := new(UpdateAcctResponse)
	err := grpc.Invoke(ctx, "/account.AccountApi/UpdateAcct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountApi service

type AccountApiServer interface {
	CreateAcct(context.Context, *CreateAcctRequest) (*CreateAcctResponse, error)
	ListAcct(context.Context, *ListAcctRequest) (*ListAcctResponse, error)
	ShowAcct(context.Context, *ShowAcctRequest) (*ShowAcctResponse, error)
	DeleteAcct(context.Context, *DeleteAcctRequest) (*DeleteAcctResponse, error)
	UpdateAcct(context.Context, *UpdateAcctRequest) (*UpdateAcctResponse, error)
}

func RegisterAccountApiServer(s *grpc.Server, srv AccountApiServer) {
	s.RegisterService(&_AccountApi_serviceDesc, srv)
}

func _AccountApi_CreateAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreateAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AccountApiServer).CreateAcct(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AccountApi_ListAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AccountApiServer).ListAcct(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AccountApi_ShowAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ShowAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AccountApiServer).ShowAcct(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AccountApi_DeleteAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AccountApiServer).DeleteAcct(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _AccountApi_UpdateAcct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UpdateAcctRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(AccountApiServer).UpdateAcct(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _AccountApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountApi",
	HandlerType: (*AccountApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAcct",
			Handler:    _AccountApi_CreateAcct_Handler,
		},
		{
			MethodName: "ListAcct",
			Handler:    _AccountApi_ListAcct_Handler,
		},
		{
			MethodName: "ShowAcct",
			Handler:    _AccountApi_ShowAcct_Handler,
		},
		{
			MethodName: "DeleteAcct",
			Handler:    _AccountApi_DeleteAcct_Handler,
		},
		{
			MethodName: "UpdateAcct",
			Handler:    _AccountApi_UpdateAcct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0xed, 0x8f, 0x7e, 0x86, 0x4f, 0x5b, 0xaf, 0x4c, 0xd9, 0x80, 0x61, 0xd1, 0x55, 0x25, 0xda,
	0x13, 0x54, 0x14, 0xba, 0x61, 0x05, 0xe2, 0x00, 0x21, 0xb1, 0x44, 0x54, 0x48, 0x4c, 0xec, 0xa8,
	0xe2, 0xd0, 0xdc, 0x01, 0xc7, 0x89, 0xeb, 0x51, 0x12, 0x24, 0xc2, 0xa2, 0x52, 0x67, 0x3c, 0xf3,
	0xde, 0xcc, 0x7b, 0xa3, 0xc0, 0xa9, 0xe7, 0xfb, 0x71, 0x1a, 0xa9, 0x85, 0x48, 0x62, 0x15, 0x93,
	0x41, 0x11, 0xb2, 0x1d, 0x0c, 0xd6, 0xf9, 0x5f, 0x02, 0xd0, 0x09, 0x03, 0xda, 0xbe, 0x6c, 0xcf,
	0x47, 0xe4, 0x04, 0x7a, 0x91, 0xf7, 0xc1, 0x69, 0xc7, 0x44, 0x67, 0xd0, 0xf7, 0x44, 0xb8, 0xe3,
	0x5f, 0xb4, 0x6b, 0x63, 0xa9, 0x3c, 0x95, 0x4a, 0xda, 0x33, 0xb1, 0x6e, 0xf5, 0x13, 0xee, 0x29,
	0xbe, 0xd1, 0x3f, 0x7a, 0xa4, 0x73, 0xdd, 0x2c, 0x17, 0xf0, 0x77, 0x5e, 0xe4, 0xfa, 0x59, 0x8e,
	0xad, 0x60, 0x7a, 0x67, 0xea, 0x34, 0xa5, 0x7a, 0xe2, 0x9f, 0x29, 0x97, 0x2a, 0xa3, 0xd2, 0xc3,
	0xa8, 0x82, 0x78, 0x02, 0x43, 0x99, 0x0a, 0x9e, 0x64, 0x64, 0x86, 0x9c, 0xdd, 0x00, 0xc1, 0x4d,
	0x52, 0xc4, 0x91, 0xe4, 0x68, 0x04, 0xd3, 0xc7, 0xae, 0x61, 0xfc, 0x18, 0x4a, 0x85, 0x81, 0x31,
	0x54, 0x5e, 0x74, 0x0f, 0x13, 0x57, 0x54, 0x00, 0x5d, 0x81, 0xd5, 0x42, 0x17, 0x75, 0xe7, 0xc7,
	0xcb, 0xc9, 0xc2, 0x4a, 0x65, 0x85, 0x71, 0x5c, 0xf9, 0x44, 0xb7, 0x30, 0x7e, 0x7e, 0x8b, 0xf7,
	0x4d, 0x96, 0xd0, 0xcc, 0xae, 0xa5, 0x8e, 0xb9, 0xfd, 0x27, 0x66, 0x2d, 0xe0, 0xc6, 0x88, 0xda,
	0x50, 0x40, 0xdc, 0xf4, 0x8b, 0x80, 0x0f, 0x30, 0x7d, 0x11, 0x41, 0x33, 0x6f, 0xc8, 0x14, 0x46,
	0x11, 0xdf, 0xe3, 0xdb, 0x60, 0x5b, 0x20, 0x18, 0xe7, 0xdf, 0xbb, 0x2e, 0xbf, 0x3b, 0x00, 0xc5,
	0xdb, 0x5a, 0x84, 0x64, 0x0b, 0xe0, 0xce, 0x80, 0xcc, 0x0e, 0xed, 0x95, 0x83, 0x9a, 0x5d, 0xd4,
	0xbe, 0xe5, 0x83, 0xb0, 0x16, 0x59, 0xc3, 0xd0, 0x1e, 0x01, 0xa1, 0x87, 0xd2, 0xd2, 0xf1, 0xcc,
	0xce, 0x6b, 0x5e, 0x30, 0x84, 0x75, 0x13, 0x41, 0x94, 0x6e, 0x02, 0x41, 0x94, 0xad, 0xd7, 0x10,
	0x7a, 0x1d, 0x67, 0x0a, 0x5a, 0xa7, 0x62, 0x2f, 0x5a, 0xa7, 0xea, 0x62, 0x0e, 0xe4, 0xf4, 0x46,
	0x40, 0x15, 0x33, 0x11, 0x50, 0xd5, 0x20, 0xd6, 0x7a, 0xed, 0x9b, 0x2f, 0xc3, 0xea, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x73, 0x93, 0xad, 0x83, 0x2a, 0x04, 0x00, 0x00,
}
